spring:
  h2:
    console:
      enabled: 'true'
      path: /h2-console
  jpa:
    properties:
      hibernate:
        dialect:
          nodeValue: org.hibernate.dialect.MySQL57Dialect
          storage_engine: innodb
    show-sql: 'true'
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    hikari:
      jdbc-url: jdbc:h2:mem://localhost/~/test;MODE=MYSQL

