server:
  port: 5000
spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  jpa:
    database: MYSQL
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.db.name}
    username: ${rds.username}
    password: ${rds.password}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${GITHUB_ID}
            clientSecret: ${GITHUB_SECRET}
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user
          google:
            clientId: ${GOOGLE_ID}
            clientSecret: ${GOOGLE_SECRET}
            redirectUri: "https://api.wsiwt.store/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile


    provider:
      github:
        authorization-uri: https://github.com/login/oauth/authorize
        token-uri: https://github.com/login/oauth/access_token
        user-info-uri: https://api.github.com/user
      google:
        authorization-uri: https://google.com/login/oauth/authorize

weather_apikey: ${WEATHER_API_KEY}
kakao_key: ${KAKAO_KEY}
cloudinary_url: ${CLOUDINARY_URL}
cloudinary_preset: ${CLOUDINARY_PRESET}
city_key : ${CITY_KEY}