# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./WSIWT_BACK
    permissions:
      contents: read
      packages: write

    - name: Login to Docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./WSIWT_BACK/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/node-project:latest

        - name: Beanstalk Deploy
            uses: einaregilsson/beanstalk-deploy@v20
            with:
              aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              application_name: ${{ secrets.AWS_APPLICATION_NAME }}
              environment_name: ${{ secrets.AWS_ENVIRONMENT_NAME }}
              region: us-west-2
              deployment_package: Dockerrun.aws.json

 
